# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: '2.1'
orbs:
  flutter: circleci/flutter@2.0.0
jobs:
  distribute:
    macos:
      xcode: 12.5.1
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.0.3
      - flutter/install_ios_pod
      - flutter/install_ios_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: ios
workflows:
  distribute:
    jobs:
      - distribute

